#! /usr/bin/env bash

set -u
set -e
set -o pipefail

todo=${1:-}
due_date=${2:-}
amount=${3:-}
description=${@:4}

[ ! -z "$todo" ] || exit 110
[ -f "$todo" ] || exit 110

exec cat <<EOF >>"$todo"
0 (by $due_date) $amount $description
EOF
