#! /usr/bin/env bash

set -u
set -e
set -o pipefail

todo=${1:-}

[ ! -z "$todo" ] || exit 110
[ -f "$todo" ] || exit 110

exec watch 'todo-cat '"$todo"' | todo-filter-all-undone | todo-filter-today'
